### Register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

 {
   "username": "isinghdivyanshu",
   "email": "singhdivyanshu2707@gmail.com",
   "password": "password123"
 }