CREATE TABLE chapters
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(20)                             NOT NULL,
    content  TEXT                                    NOT NULL,
    story_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_chapters PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE stories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(1500),
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_stories PRIMARY KEY (id)
);

CREATE TABLE story_genres
(
    genre_id BIGINT NOT NULL,
    story_id BIGINT NOT NULL,
    CONSTRAINT pk_story_genres PRIMARY KEY (genre_id, story_id)
);

CREATE TABLE story_tags
(
    story_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    CONSTRAINT pk_story_tags PRIMARY KEY (story_id, tag_id)
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username           VARCHAR(20)                             NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    is_verified        BOOLEAN                                 NOT NULL,
    verification_token VARCHAR(255),
    token_expiration   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE chapters
    ADD CONSTRAINT FK_CHAPTERS_ON_STORY FOREIGN KEY (story_id) REFERENCES stories (id);

ALTER TABLE stories
    ADD CONSTRAINT FK_STORIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE story_genres
    ADD CONSTRAINT fk_stogen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);

ALTER TABLE story_genres
    ADD CONSTRAINT fk_stogen_on_story FOREIGN KEY (story_id) REFERENCES stories (id);

ALTER TABLE story_tags
    ADD CONSTRAINT fk_stotag_on_story FOREIGN KEY (story_id) REFERENCES stories (id);

ALTER TABLE story_tags
    ADD CONSTRAINT fk_stotag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);