CREATE TABLE characters
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    story_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

ALTER TABLE characters
    ADD CONSTRAINT uc_characters_name UNIQUE (name);

ALTER TABLE characters
    ADD CONSTRAINT FK_CHARACTERS_ON_STORY FOREIGN KEY (story_id) REFERENCES stories (id);